
name: 01-ondemand-create-release
run-name: Creating Release ${{ inputs.ReleaseNo }}
on:
  workflow_dispatch:
   inputs:
      ReleaseNo:
        description: 'Enter Release name'
        required: true
        default: '2.5.3'

env:
  WORKFLOW_VARIABLE: WORKFLOW

jobs:
  pre_check:
     runs-on: [ubuntu-org,ubuntu-org4]
     steps:
      - name: "checkout"
        uses: actions/checkout@v2
#      - name: Set up Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }} 
#      - name: Install dependencies
#        run: npm install
#      - name: sample curl call
#        run: |
#          curl https://meowfacts.herokuapp.com/ | jq '.data[0]'
#        id: samplecurl
#      - name: Set the value
#        id: step_one
#        run: |
#          echo "test=$(curl https://meowfacts.herokuapp.com/ | jq '.data[0]' )" >> $GITHUB_ENV
#      - name: Use the value
#        id: step_two
#        run: |
#          echo "$test" # This will output 'yellow'
      - name: "Perform SOD Check"
        run: |
          echo "Perform SOD Check" 
      - name: "create service now ticket"
        run: |
          echo "create service now ticket" 
  release-initiation:
     runs-on: [ubuntu-org,ubuntu-org4]
     needs: pre_check
     steps:
      - name: "create sharepoint folder"
        run: |
          echo "sharepoint folder creation" 
      - name: "create an workitem for Compliance team"
        id: compliancewkitem
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ SECRETS.GIT_PER_TOKEN }}
          owner: imurpalvicky-org
          repo: compliance-team
          title: New Release -<GEAR_ID>-${{ github.event.inputs.ReleaseNo }} ADM Approval
          body: |
            # Body
            New Release created verify the artifacts and close the issue with the comment "APPROVED"
          assignees: imurpalvicky
          labels: CHG459 ,gearid-1234
      - name: "create an workitem for App Release engineer team to kick start the release"
        id: releaseEnggwkitem
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ SECRETS.GIT_PER_TOKEN }}
          title: New Release-<GEAR_ID>- ${{ github.event.inputs.ReleaseNo }} waiting for change window
          body:  |
            # Body
            Please close the issue  once the ADM approval is given, with the comment "GET STARTED" 
          assignees: imurpalvicky
          labels: CHG459 ,gearid-1234
      - name: "summary creation"
        run: |
            echo "summary created"
            SUMMARY=$'# Job Summary\n## Two GitHub workitem are created  \n successful \n '
            echo "$SUMMARY Compliance team need to Approve this ${{ steps.compliancewkitem.outputs.html_url }} ---------- Release engineer to start the release ${{ steps.releaseEnggwkitem.outputs.html_url }}  " >> $GITHUB_STEP_SUMMARY
