
name: implement release Workflow

on:
  issues:
    types: [opened, closed, reopened]
jobs:
  payloadprintjob:
    if: contains(github.event.issue.labels.*.name, 'gearid-1234')
    name: Print event
    runs-on: [ubuntu-org,ubuntu-org4]
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{toJson(github)}}
        issuelabels: "${{ join(github.event.issue.labels.*.name,',') }}"
      run: |
        echo " this is the issue action ${{ github.event.action }}" 
        echo "this is the issue lable ${{ join(github.event.issue.labels.*.name,';') }}"
          
    - uses: octokit/request-action@v2.x
      id: get_adm_issue_status
      with:
        route: GET "/repos/imurpalvicky-org/compliance-team/issues/?labels={issuelabels}"
        owner: octokit
        repo: request-action
        issuelabels: ${{env.issuelabels}}
      env:
        GITHUB_TOKEN: ${{ SECRETS.GIT_PER_TOKEN }}
        
    - name: "Check if the ADM team approved the release"
      if: "${{toJson(steps.get_adm_issue.outputs.data[0].state) == 'open'}}"
      run: |
        echo "Release Approved by ADM team " 
    - run: "echo latest release: '${{ steps.get_adm_issue.outputs.data }}'"
