
name: implement release Workflow

on:
  issues:
    types: [opened, closed, reopened]
jobs:
  pre-implementation-job:
    if: contains(github.event.issue.labels.*.name, 'gearid-1234')
    name: Pre-release-implementation
    runs-on: [ubuntu-org,ubuntu-org4]
    steps:
    - name: set env Variables
      env:
        GITHUB_CONTEXT: ${{toJson(github)}}
        issuelabels: "${{ join(github.event.issue.labels.*.name,',') }}"
      run: |
        echo "labels=${{ join(github.event.issue.labels.*.name,',') }}" >> $GITHUB_ENV
        echo " this is the issue action ${{ github.event.action }}" 
        echo "this is the issue lable ${{ join(github.event.issue.labels.*.name,',') }}"
          
    - uses: octokit/request-action@v2.x
      name: Get ADM issue status
      id: get_adm_issue_status
      with:
        route: GET /repos/{owner}/{repo}/issues
        repo: 'compliance-team'
        owner: 'imurpalvicky-org'
        labels: ${{ env.labels }}
      env:
        GITHUB_TOKEN: ${{ SECRETS.GIT_PER_TOKEN }}
        
    - name: "ADM approval provided is closed?"
      if: ${{fromJson(steps.get_adm_issue_status.outputs.data)[0].state == 'closed'}} 
      run: |
        echo "Release Approved by ADM team as ${{fromJson(steps.get_adm_issue_status.outputs.data)[0].state}}" 
    - name: "ADM approval provided is not closed?"
      if: ${{fromJson(steps.get_adm_issue_status.outputs.data)[0].state != 'closed'}}
      run: |
        echo "Release disapproved by ADM team as ${{fromJson(steps.get_adm_issue_status.outputs.data)[0].state}}" 
        exit 1
  RunDeploy-job:
      needs: pre-implementation-job
      runs-on: [ubuntu-org,ubuntu-org4]
      steps:
      - name: "Jenkins deployment Job"
        run: |
          echo "Run Jenkins job and wait for two hours "
