
name: implement release Workflow

on:
  issues:
    types: [opened, closed, reopened]
jobs:
  payloadprintjob:
    if: contains(github.event.issue.labels.*.name, 'gearid-1234')
    name: Print event
    runs-on: [ubuntu-org,ubuntu-org4]
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ github.event.issue.labels.*.name }}
      run: |
        echo " this is the issue action ${{ github.event.issue.action }}" 
        echo "this is the issue lable ${{ github.event.issue.labels.*.name }}" 
